#compdef jari
# jari zsh completion
# Generated by: jari completions zsh

_jari() {
    local context state state_descr line
    typeset -A opt_args
    _arguments -C \
        '--config[Config file path]:file:_files' \
        '--url[Jira base URL]:url:' \
        '--email[Jira email]:email:' \
        '--token[API token]:token:' \
        '--output[Output format]:format:(json json-pretty)' \
        '-v[Enable verbose logging]' \
        '--verbose[Enable verbose logging]' \
        '-h[Print help]' \
        '--help[Print help]' \
        '1: :->cmd' \
        '*:: :->args'

    case "$state" in
        cmd)
            _values 'command' \
                'issue[Issue operations]' \
                'search[Search with JQL]' \
                'transition[Workflow transitions]' \
                'comment[Comment operations]' \
                'project[Project operations]' \
                'field[Field operations]' \
                'me[Current user info]' \
                'config[Configuration]' \
                'schema[Schema generation]' \
                'completions[Shell completions]'
            ;;
        args)
            case $line[1] in
                issue)
                    _values 'issue subcommand' \
                        'get[Get issue details]' \
                        'create[Create issue]' \
                        'edit[Edit issue]' \
                        'delete[Delete issue]' \
                        'assign[Assign issue]' \
                        'watch[Watch operations]'
                    ;;
                transition)
                    _values 'transition subcommand' \
                        'list[List transitions]' \
                        'do[Execute transition]'
                    ;;
                comment)
                    _values 'comment subcommand' \
                        'list[List comments]' \
                        'get[Get comment]' \
                        'add[Add comment]'
                    ;;
                project)
                    _values 'project subcommand' \
                        'list[List projects]' \
                        'get[Get project]'
                    ;;
                field)
                    _values 'field subcommand' \
                        'list[List fields]'
                    ;;
                config)
                    _values 'config subcommand' \
                        'show[Show config]' \
                        'path[Show config path]' \
                        'init[Initialize config]'
                    ;;
                completions)
                    _values 'shell' 'bash' 'zsh' 'fish'
                    ;;
            esac
            ;;
    esac
}

_jari
