# jari bash completion
# Generated by: jari completions bash
_jari() {
    local i cur prev opts cmd
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cmd=""
    opts=""

    for i in ${COMP_WORDS[@]}; do
        case "${cmd},${i}" in
            ",jari") cmd="jari";;
            jari,issue) cmd="jari__issue";;
            jari,search) cmd="jari__search";;
            jari,transition) cmd="jari__transition";;
            jari,comment) cmd="jari__comment";;
            jari,project) cmd="jari__project";;
            jari,field) cmd="jari__field";;
            jari,config) cmd="jari__config";;
            jari,completions) cmd="jari__completions";;
            jari,schema) cmd="jari__schema";;
            *) ;;
        esac
    done

    case "${cmd}" in
        jari)
            opts="-h -V --help --version --config --url --email --token --output -v --verbose issue search transition comment project field me config schema completions"
            ;;
        jari__issue)
            opts="-h --help get create edit delete assign watch"
            ;;
        jari__search|jari__transition|jari__comment|jari__project|jari__field|jari__config|jari__schema|jari__completions)
            COMPREPLY=()
            ;;
        *)
            ;;
    esac

    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
}
complete -F _jari jari
