# jari fish completion
# Generated by: jari completions fish
complete -c jari -f
complete -c jari -l config -d 'Config file path' -r
complete -c jari -l url -d 'Jira base URL' -r
complete -c jari -l email -d 'Jira email' -r
complete -c jari -l token -d 'API token' -r
complete -c jari -l output -d 'Output format: json, json-pretty' -r
complete -c jari -s v -l verbose -d 'Enable verbose logging'
complete -c jari -s h -l help -d 'Print help'
complete -c jari -n '__fish_use_subcommand' -a 'issue' -d 'Issue operations'
complete -c jari -n '__fish_use_subcommand' -a 'search' -d 'Search with JQL'
complete -c jari -n '__fish_use_subcommand' -a 'transition' -d 'Workflow transitions'
complete -c jari -n '__fish_use_subcommand' -a 'comment' -d 'Comment operations'
complete -c jari -n '__fish_use_subcommand' -a 'project' -d 'Project operations'
complete -c jari -n '__fish_use_subcommand' -a 'field' -d 'Field operations'
complete -c jari -n '__fish_use_subcommand' -a 'me' -d 'Current user info'
complete -c jari -n '__fish_use_subcommand' -a 'config' -d 'Configuration'
complete -c jari -n '__fish_use_subcommand' -a 'schema' -d 'Schema generation'
complete -c jari -n '__fish_use_subcommand' -a 'completions' -d 'Shell completions'
